### PR TITLE
[AD-614] Bump version to v1.2.0

### PR DESCRIPTION
**Pull request by andiemontoyeah**
### Summary

Bumps driver version to v1.2.0 from v1.1.1 for next minor release.

### Related Issue
https://bitquill.atlassian.net/browse/AD-614

### Additional Reviewers
@affonsoBQ
@andiem-bq
@alexey-temnikov
@birschick-bq

### CODE REVIEW

**Comment by andiem-bq** [comment]
Waiting for #294 and #295 then will rebase

**Review by alinaliBQ — APPROVED** [review]
Looks good to me! but I have a question: I thought the AD-627 (add getaggregate function) is merged to develop in [this PR](https://github.com/aws/amazon-documentdb-jdbc-driver/pull/295/files)? Why is it showing in this PR also? Just a little confused

**Comment by andiemontoyeah** [comment]
> Looks good to me! but I have a question: I thought the AD-627 (add getaggregate function) is merged to develop in [this PR](https://github.com/aws/amazon-documentdb-jdbc-driver/pull/295/files)? Why is it showing in this PR also? Just a little confused

I messed up and didnt notice hehe 😅

**Comment by alinaliBQ** [comment]
> > Looks good to me! but I have a question: I thought the AD-627 (add getaggregate function) is merged to develop in [this PR](https://github.com/aws/amazon-documentdb-jdbc-driver/pull/295/files)? Why is it showing in this PR also? Just a little confused
> 
> I messed up and didnt notice hehe 😅

haha no worries!

**Review by alexey-temnikov — APPROVED** [review]

**Review by birschick-bq — APPROVED** [review]

**Pull request merged**
